version: "3"
services:
    usuario.api:
        image: mechlovers/usuario.api
        container_name: usuario.api
        build:
            context: .
            dockerfile: /src/backend/services/usuario.api/Dockerfile
        ports:
            - "9001:3000"
        links:
            - sql.data
        depends_on:
            - sql.data
            - rabbitmq
            
    sql.data:
        image: mechlovers/mysql
        container_name: mysql
        build:
            context: .
            dockerfile: /src/database/Dockerfile
        environment:            
            - MYSQL_USER=mechlovers
            - MYSQL_PASSWORD=mechlovers
            - MYSQL_ROOT_PASSWORD=supersecret
        ports:
            - 3306:3306    
    
    nosql.data:
        image: mongo
        container_name: mongo
    
    cache.store:
        image: memcached
        container_name: memcached

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq