version: "3"
services:
    usuario.api:
        image: mechlovers/usuario.api
        container_name: usuario.api
        build:
            context: .
            dockerfile: /src/backend/services/usuario.api/Dockerfile
        volumes:
            - /src/backend/services/usuario.api:/app
        ports:
            - "15002:3000"
        links:
            - sql.data
        depends_on:
            - sql.data
            - rabbitmq
        networks:
            - mechlovers_network

    api.gateway:
        image: mechlovers/api.gateway
        container_name: api.gateway
        build:
            context: .
            dockerfile: /src/backend/services/api.gateway/Dockerfile
        volumes:
            - /src/backend/services/api.gateway:/app
        ports:
            - "15000:8080"
            - "15001:9876"
        links:
            - usuario.api
        depends_on:
            - usuario.api
        networks:
            - mechlovers_network
            
    sql.data:
        image: mechlovers/mysql
        container_name: mysql
        build:
            context: .
            dockerfile: /src/database/Dockerfile
        environment:            
            - MYSQL_USER=mechlovers
            - MYSQL_PASSWORD=mechlovers
            - MYSQL_ROOT_PASSWORD=supersecret
        ports:
            - 3306:3306    
        networks:
            - mechlovers_network
    
    nosql.data:
        image: mongo
        container_name: mongo
        networks:
            - mechlovers_network
    
    cache.store:
        image: memcached
        container_name: memcached
        networks:
            - mechlovers_network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        networks:
            - mechlovers_network

networks:
    mechlovers_network:
        driver: bridge