version: "3"
services:
    usuario.api:
        image: usuario.api
        container_name: usuario.api
        build:
            context: .
            dockerfile: app/src/backend/services/usuario.api/Dockerfile
        ports:
            - "8081:80"
        volumes:
            app/src/backend/services/usuario.api:/app
        links:
            - db
        depends_on:
            - db
    db:
        image: "mysql:8"
        container_name: mysql
        ports:
            - 3306:3306        
        volumes:
            - app/src/backend/database:/var/lib/mysql
        environment:        
            MYSQL_USER: "mechlovers"
            MYSQL_PASSWORD: "mechlovers"    
            MYSQL_ROOT_PASSWORD: "admin"