http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  usuario_api:
    host: usuario_api
    paths: '/usuario'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usuario_api:
    url: 'http://usuario.api:3000/usuario/1'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  usuarioApi:
    apiEndpoints:
      - usuario_api
    policies:
      - proxy:
          - action:
              serviceEndpoint: usuario_api 
              changeOrigin: true
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
